---
openapi: "3.0.0"
info:
  title: "Perevozka API"
  version: "1.0.0"
paths:
  /api/registration:
    post:
      tags:
        - Authentication
      description: "Registration company form. Required fiels - email, password, phone_number, company_name, legal_address, postal_address, role_id | Role_id _ 1-OWNER, 2-DRIVER, 3-OWNER AND DRIVER"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: "email@mail.ru"
                phone_number:
                  required: true
                  example: "89186655444"
                  type: string
                password:
                  required: true
                  example: "gaspar777"
                  minimum: 8
                  type: string
                company_name:
                  required: true
                  example: "Sberbank"
                  type: string
                legal_address:
                  required: true
                  example: "Wall street"
                  type: string
                postal_address:
                  required: true
                  example: "3315"
                  type: string
                role_id:
                  required: true
                  example: 1
                  type: integer
                inn:
                  required: false
                  type: string
                ogrn:
                  required: false
                  type: string
                logo_url:
                  required: false
                  type: string
                favorites:
                  required: false
                  type: string
      responses:
        200:
          description: 'Company successfully created'
      security:
        - bearerAuth: [ ]
  /api/login:
    post:
      tags:
        - Authentication
      description: "Login company form"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: "email@mail.ru"
                password:
                  required: true
                  example: "gaspar777"
                  minimum: 8
                  type: string
      responses:
        200:
          description: 'Successfully logged in'
      security:
        - bearerAuth: [ ]
  /api/makeDisabled/{id}:
    post:
      tags:
        - Api's
      description: "Make order disabled"
      parameters:
        - in: path
          name: id
          required: true
          description: "Order id"
      responses:
        200:
          description: 'Successfully logged in'
        404:
          description: "Order not found"
      security:
        - bearerAuth: [ ]
  /api/favorite/list:
    get:
      tags:
        - Favorites
      description: "User favorite list"
      responses:
        200:
          description: 'Successfully logged in'
      security:
        - bearerAuth: [ ]

  /api/favorite/add:
    post:
      tags:
        - Favorites
      description: "Add order in favorite list"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
                  required: true
                  example: 1
                order_type:
                  type: string
                  required: true
                  example: "good"
      responses:
        200:
          description: 'Successfully logged in'
      security:
        - bearerAuth: [ ]
  /api/favorite/delete:
      post:
        tags:
          - Favorites
        description: "Remove order from favorite list"
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                    required: true
                    example: 1
                  order_type:
                    type: string
                    required: true
                    example: "good"
        responses:
          200:
            description: 'Successfully logged in'
        security:
          - bearerAuth: [ ]
  /api/user:
    get:
      tags:
        - Api's
      responses:
        200:
          description: 'Successfully logged in'
      security:
        - bearerAuth: [ ]

  /api/manager/create:
    post:
      tags:
        - Manager
      description: "Create manager"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company_id:
                  type: integer
                  required: true
                  example: 1
                first_name:
                  type: string
                  required: true
                  example: "Pavel"
                last_name:
                  type: string
                  required: true
                  example: "Pavleashvili"
      responses:
        200:
          description: 'Successfully created'
      security:
        - bearerAuth: [ ]

  /api/manager/delete/{id}:
    post:
      tags:
        - Manager
      description: "Delete manager"
      parameters:
        - in: path
          name: id
          required: true
          description: "Manager id"
      responses:
        200:
          description: 'Successfully logged in'
      security:
        - bearerAuth: [ ]

components:
  schemas:
    Company:
      required:
        - email
        - password
        - phone_number
        - company_name
        - legal_address
        - postal_address
        - role_id
      type: object
      properties:
        email:
          type: string
          example: email@mail.ru
        password:
          type: string
          example: email777
        phone_number:
          type: string
          example: 89186655444
        company_name:
          type: string
          example: Sberbank
        legal_address:
          type: string
          example: Wall street
        mail_address:
          type: string
          example: 3315 Gyumri
        role_id:
          type: integer
          example: 2
          description: 1 - OWNER, 2 - DRIVER, 3 - OWNER AND DRIVER
#    Category:
#      required:
#        - categories
#        - category_info
#        - title
#        - language_code
#        - ordering
#        - parent_id
#        - category_info
#      type: object
#      properties:
#        parent_id:
#          type: integer
#          format: int64
#          example: 10
#          description: If the category is parent  category need send 0
#        ordering:
#          type: integer
#          format: int64
#          example: 10
#        category_info:
#          type: array
#          xml:
#            wrapped: true
#          items:
#            type: object
#            properties:
#              title:
#                type: string
#                example: Development
#              language_code:
#                type: string
#                example: "hy"
#    Course:
#      required:
#        - id
#        - type
#      type: object
#      properties:
#        data:
#          type: array
#          items:
#            type: object
#            properties:
#              id:
#                type: integer
#                format: int64
#                example: 1
#              type:
#                type: integer
#                format: int64
#                example: 1
#              category_id:
#                type: integer
#                format: int64
#                example: 1
#              trainer_id:
#                type: integer
#                format: int64
#                example: 1
#              title:
#                type: string
#                example: title course
#              sub_title:
#                type: string
#                example: sub title course
#              description:
#                type: string
#                example: description course
#              language:
#                type: integer
#                example: 1
#              status:
#                type: integer
#                example: 1
#              price:
#                type: integer
#                example: 1.1
#              max_participants:
#                type: integer
#                example: 1
#              level:
#                type: number
#                example: 1.1
#              currency:
#                type: string
#              promo_video:
#                type: string
#                format: binary
#              cover_image:
#                type: string
#                format: binary
#              lessons:
#                type: array
#                xml:
#                  wrapped: true
#                items:
#                  type: object
#                  properties:
#                    title:
#                      type: string
#                      example: Laravel
#                    course_id:
#                      type: integer
#                      example: 1
#                    duration:
#                      type: integer
#                      example: 1
#                    start_time:
#                      type: string
#                      example: 2022-10-10 10:12:00
#              trainer:
#                type: object
#                properties:
#                  first_name:
#                    type: string
#                    example: Trainer
#                  last_name:
#                    type: string
#                    example: Trainer
#                  bio:
#                    type: string
#                    example: bio
#                  avatar:
#                    type: string
#        current_page:
#          type: integer
#          example: 1
#        first_page_url:
#          type: integer
#          example: "string"
#        from:
#          type: integer
#          example: 1
#        last_page:
#          type: integer
#          example: 1
#        last_page_url:
#          type: string
#          example: "http://api.loc/api/v1/courses?page=5"
#        next_page_url:
#          type: string
#          example: "http://api.loc/api/v1/courses?page=4"
#        per_page:
#          type: string
#          example: 1
#        prev_page_url:
#          example: "http://api.loc/api/v1/courses?page=2"
#        to:
#          type: integer
#          example: 1
#        total:
#          type: integer
#          example: 1
#    Trainer:
#      type: object
#      properties:
#        id:
#          type: integer
#          format: int64
#          example: 1
#        user_id:
#          type: integer
#          format: int64
#          example: 1
#        first_name:
#          type: string
#        last_name:
#          type: string
#        bio:
#          type: string
#        avatar:
#          type: string
#    Moderator:
#      type: object
#      properties:
#        first_name:
#          type: "string"
#        last_name:
#          type: "string"
#        email:
#          type: "string"
#        password:
#          type: "string"
#        company_name:
#          type: "string"
#        role_id:
#          type: integer
#          default: 2
#        tax_identity_number:
#          type: "integer"
#    Notification:
#      type: object
#      properties:
#        id:
#          type: "integer"
#        title:
#          type: "string"
#        message:
#          type: "string"
#        type:
#          type: "string"
#        status:
#          type: "integer"
#        created_at:
#          type: "string"
#    Lesson:
#      type: object
#      properties:
#        id:
#          type: "integer"
#        title:
#          type: "string"
#        course_id:
#          type: "integer"
#        section_id:
#          type: "integer"
#        type:
#          type: "string"
#        video_url:
#          type: "string"
#        article:
#          type: "string"
#        position:
#          type: "integer"
#    Question:
#      type: object
#      properties:
#        quiz_id:
#          type: "integer"
#          required: false
#          example: 1
#        section_id:
#          type: "integer"
#          required: false
#          example: 1
#        question:
#          type: "string"
#        answers:
#          type: "array"
#          example: ['answer1', 'answer2']
#        right_answers:
#          type: "array"
#          example: ['right_answer1', 'right_answer2']
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT





